"""Deploy database

Revision ID: 25c6b2a3b7fb
Revises: 
Create Date: 2025-03-08 04:07:03.654980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25c6b2a3b7fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('meet_link', sa.String(length=60), server_default='none', nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Done', 'Cancelled', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('services', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
